# ==========================================================================
# Copyright 2019 Jomoespe. All rights reserved.
#
# Use of this source code is governed by a The Unlicense license that can be
# found in the LICENSE file.
# ==========================================================================

FROM alpine:3.14.2
ENTRYPOINT [ "cat", "/file.txt" ]
